FROM rust:1.80-alpine AS builder
WORKDIR /app
RUN apk add --no-cache musl-dev g++ clang make
COPY core-engine/Cargo.toml ./
COPY core-engine/src ./src
COPY core-engine/include ./include
RUN cargo build --release

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/target/release/flux_core_runner .
CMD ["./flux_core_runner"]
