FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY saas-control/go.mod ./
COPY saas-control/*.go ./
RUN CGO_ENABLED=0 GOOS=linux go build -o saas_server main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/saas_server .
EXPOSE 8080
CMD ["./saas_server"]
